name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.12"]
        os: [unbutu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: action/checkou@v2
      - uses: action/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install .[test]
      - name: Run tests
        run: pytest --v tests integration